version: "3.9"
services:
  db:
    image: postgres:latest
    volumes:
      - dbstorage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: ./webapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./webapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  rec:
    build: ./rec
    volumes:
      - ./rec:/rec
    ports:
      - "5000:5000"

volumes:
    dbstorage:
